name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Connect to EC2 and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          
          # Ensure the project directory exists
          mkdir -p /home/ubuntu/app
          cd /home/ubuntu/app

          # Initialize git if needed
          if [ ! -d ".git" ]; then
            git init
            git remote add origin ${{ secrets.DEPLOY_REPO_URL }}
          fi

          # Pull latest changes
          git reset --hard
          git pull origin main

          # -------- Deploy Authentication Service --------
          cd backend/authentication-service

          # Stop & Remove existing container
          docker stop auth-service || true
          docker rm auth-service || true

          # Build & Run authentication-service
          docker build -t authentication-service .
          docker run -d -p 5001:5001 --env-file .env --name auth-service authentication-service

          # Wait for it to start
          sleep 5
          docker ps -a

          # -------- Deploy Checklist Service --------
          cd ../checklist-service

          # Stop & Remove existing container
          docker stop checklist-service || true
          docker rm checklist-service || true

          # Build & Run checklist-service
          docker build -t checklist-service .
          docker run -d -p 5002:5002 --env-file .env --name checklist-service checklist-service

          # Wait for it to start
          sleep 5
          docker ps -a

          # Show logs after startup
          docker logs -f auth-service
          docker logs -f checklist-service
        EOF
