name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Connect to EC2 and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          
          # Go to project directory
          mkdir -p app
          cd /home/ubuntu/app

          # Ensure repository is initialized correctly
          if [ ! -d ".git" ]; then 
            git init .
            git remote add origin ${{ secrets.DEPLOY_REPO_URL }}
          fi

          # Pull latest changes
          git pull origin main

          # Deploy Authentication Service
          cd backend/authentication-service
          
          docker stop auth-service || true
          docker rm auth-service || true

          docker build -t authentication-service .
          docker run -d -p 5001:5001 --env-file /home/ubuntu/app/backend/authentication-service/.env --name auth-service authentication-service

          # Deploy Checklist Service
          cd ../checklist-service

          docker stop checklist-service || true
          docker rm checklist-service || true

          docker build -t checklist-service .
          docker run -d -p 5002:5002 --env-file /home/ubuntu/app/backend/checklist-service/.env --name checklist-service checklist-service

          # Display running containers
          docker ps -a

          # Show logs
          docker logs -f checklist-service
        EOF
